export interface Project {
  id: string;
  name: string;
  client: string;
  type: 'Editorial' | 'Commercial' | 'Social';
  date: string;
}

export interface ImageAsset {
  id: string;
  url: string;
  name: string;
  isReference: boolean;
  type: 'indoor' | 'outdoor';
}

export interface LookMetrics {
  contrast: number;
  saturation: number;
  warmth: number;
  uniformity: number;
  exposure: number;
}

export interface LookVersion {
  id: string;
  name: string; // e.g., "V1 - Summer High", "V2 - Muted"
  intensity: number;
  shadows: number;
  highlights: number;
  preset: string; // 'Estate', 'Dark', 'Corporate'
  metrics: LookMetrics;
  previewUrl?: string; // Generated by Gemini
  isFavorite: boolean;
}

export interface BatchItem {
  id: string;
  originalUrl: string;
  processedUrl?: string;
  status: 'pending' | 'processing' | 'done' | 'error';
  qualityScore?: number; // 0-100 (Traffic light)
}
